{
  "c": [
    {
      "actions": {
        "finish": [],
        "init": [],
        "start": []
      },
      "adjustedMax": "",
      "adjustedMin": "",
      "alpha": 1,
      "anchorFrameType": "SCREEN",
      "anchorPoint": "CENTER",
      "animation": {
        "finish": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "main": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "start": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        }
      },
      "authorOptions": [],
      "color": [
        1,
        1,
        1,
        1
      ],
      "conditions": [],
      "config": [],
      "cooldown": false,
      "cooldownEdge": false,
      "cooldownSwipe": true,
      "cooldownTextDisabled": false,
      "desaturate": false,
      "frameStrata": 1,
      "height": 32,
      "icon": true,
      "iconSource": -1,
      "id": "Ovi'nax's Mercurial Egg BUFF 1",
      "information": [],
      "internalVersion": 78,
      "inverse": false,
      "keepAspectRatio": true,
      "load": {
        "class": {
          "multi": []
        },
        "itemequiped": [
          220305
        ],
        "size": {
          "multi": []
        },
        "spec": {
          "multi": []
        },
        "talent": {
          "multi": []
        },
        "use_itemequiped": true
      },
      "progressSource": [
        -1,
        ""
      ],
      "regionType": "icon",
      "selfPoint": "CENTER",
      "semver": "1.0.0",
      "source": "import",
      "subRegions": [
        {
          "type": "subbackground"
        },
        {
          "border_color": [
            0,
            0,
            0,
            1
          ],
          "border_edge": "Square Full White",
          "border_offset": 0,
          "border_size": 1,
          "border_visible": true,
          "type": "subborder"
        },
        {
          "anchorXOffset": 0,
          "anchorYOffset": 0,
          "rotateText": "NONE",
          "text_anchorPoint": "CENTER",
          "text_automaticWidth": "Auto",
          "text_color": [
            1,
            1,
            1,
            1
          ],
          "text_fixedWidth": 64,
          "text_font": "Friz Quadrata TT",
          "text_fontSize": 14,
          "text_fontType": "OUTLINE",
          "text_justify": "CENTER",
          "text_selfPoint": "CENTER",
          "text_shadowColor": [
            0,
            0,
            0,
            1
          ],
          "text_shadowXOffset": 0,
          "text_shadowYOffset": 0,
          "text_text": "%s",
          "text_text_format_s_format": "none",
          "text_visible": true,
          "text_wordWrap": "WordWrap",
          "type": "subtext"
        },
        {
          "anchorXOffset": 0,
          "anchorYOffset": 0,
          "rotateText": "NONE",
          "text_anchorPoint": "INNER_TOP",
          "text_anchorYOffset": 7,
          "text_automaticWidth": "Auto",
          "text_color": [
            1,
            1,
            1,
            1
          ],
          "text_fixedWidth": 64,
          "text_font": "Friz Quadrata TT",
          "text_fontSize": 11,
          "text_fontType": "OUTLINE",
          "text_justify": "CENTER",
          "text_selfPoint": "CENTER",
          "text_shadowColor": [
            0,
            0,
            0,
            1
          ],
          "text_shadowXOffset": 0,
          "text_shadowYOffset": 0,
          "text_text": "%1.tooltip",
          "text_text_format_1.tooltip1_format": "none",
          "text_text_format_1.tooltip_abbreviate": true,
          "text_text_format_1.tooltip_abbreviate_max": 3,
          "text_text_format_1.tooltip_format": "string",
          "text_text_format_p_format": "timed",
          "text_text_format_p_time_dynamic_threshold": 60,
          "text_text_format_p_time_format": 0,
          "text_text_format_p_time_legacy_floor": false,
          "text_text_format_p_time_mod_rate": true,
          "text_text_format_p_time_precision": 1,
          "text_visible": true,
          "text_wordWrap": "WordWrap",
          "type": "subtext"
        }
      ],
      "tocversion": 110005,
      "triggers": {
        "1": {
          "trigger": {
            "auranames": [
              "449578"
            ],
            "auraspellids": [
              "449578"
            ],
            "debuffType": "HELPFUL",
            "event": "Health",
            "fetchTooltip": true,
            "names": [],
            "spellIds": [],
            "subeventPrefix": "SPELL",
            "subeventSuffix": "_CAST_START",
            "type": "aura2",
            "unit": "player",
            "useExactSpellId": false,
            "useName": true,
            "use_tooltip": false
          },
          "untrigger": []
        },
        "activeTriggerMode": -10
      },
      "uid": "d)7oCDP(vbG",
      "url": "https://wago.io/MVN1rq_Hs/1",
      "useAdjustededMax": false,
      "useAdjustededMin": false,
      "useCooldownModRate": true,
      "version": 1,
      "wagoID": "MVN1rq_Hs",
      "width": 32,
      "xOffset": 0,
      "yOffset": 0,
      "zoom": 0.3
    },
    {
      "actions": {
        "finish": [],
        "init": [],
        "start": []
      },
      "adjustedMax": "",
      "adjustedMin": "",
      "alpha": 1,
      "anchorFrameType": "SCREEN",
      "anchorPoint": "CENTER",
      "animation": {
        "finish": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "main": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "start": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        }
      },
      "authorOptions": [],
      "color": [
        1,
        1,
        1,
        1
      ],
      "conditions": [],
      "config": [],
      "cooldown": false,
      "cooldownEdge": false,
      "cooldownSwipe": true,
      "cooldownTextDisabled": false,
      "desaturate": false,
      "frameStrata": 1,
      "height": 32,
      "icon": true,
      "iconSource": -1,
      "id": "Ovi'nax's Mercurial Egg BUFF 2",
      "information": [],
      "internalVersion": 78,
      "inverse": false,
      "keepAspectRatio": true,
      "load": {
        "class": {
          "multi": []
        },
        "itemequiped": [
          220305
        ],
        "size": {
          "multi": []
        },
        "spec": {
          "multi": []
        },
        "talent": {
          "multi": []
        },
        "use_itemequiped": true
      },
      "progressSource": [
        -1,
        ""
      ],
      "regionType": "icon",
      "selfPoint": "CENTER",
      "semver": "1.0.0",
      "source": "import",
      "subRegions": [
        {
          "type": "subbackground"
        },
        {
          "border_color": [
            0,
            0,
            0,
            1
          ],
          "border_edge": "Square Full White",
          "border_offset": 0,
          "border_size": 1,
          "border_visible": true,
          "type": "subborder"
        },
        {
          "anchorXOffset": 0,
          "anchorYOffset": 0,
          "rotateText": "NONE",
          "text_anchorPoint": "CENTER",
          "text_automaticWidth": "Auto",
          "text_color": [
            1,
            1,
            1,
            1
          ],
          "text_fixedWidth": 64,
          "text_font": "Friz Quadrata TT",
          "text_fontSize": 14,
          "text_fontType": "OUTLINE",
          "text_justify": "CENTER",
          "text_selfPoint": "CENTER",
          "text_shadowColor": [
            0,
            0,
            0,
            1
          ],
          "text_shadowXOffset": 0,
          "text_shadowYOffset": 0,
          "text_text": "%s",
          "text_text_format_s_format": "none",
          "text_visible": true,
          "text_wordWrap": "WordWrap",
          "type": "subtext"
        },
        {
          "anchorXOffset": 0,
          "anchorYOffset": 0,
          "rotateText": "NONE",
          "text_anchorPoint": "INNER_TOP",
          "text_anchorYOffset": 7,
          "text_automaticWidth": "Auto",
          "text_color": [
            1,
            1,
            1,
            1
          ],
          "text_fixedWidth": 64,
          "text_font": "Friz Quadrata TT",
          "text_fontSize": 11,
          "text_fontType": "OUTLINE",
          "text_justify": "CENTER",
          "text_selfPoint": "CENTER",
          "text_shadowColor": [
            0,
            0,
            0,
            1
          ],
          "text_shadowXOffset": 0,
          "text_shadowYOffset": 0,
          "text_text": "%1.tooltip",
          "text_text_format_1.tooltip_abbreviate": true,
          "text_text_format_1.tooltip_abbreviate_max": 4,
          "text_text_format_1.tooltip_format": "string",
          "text_text_format_p_format": "timed",
          "text_text_format_p_time_dynamic_threshold": 60,
          "text_text_format_p_time_format": 0,
          "text_text_format_p_time_legacy_floor": false,
          "text_text_format_p_time_mod_rate": true,
          "text_text_format_p_time_precision": 1,
          "text_visible": true,
          "text_wordWrap": "WordWrap",
          "type": "subtext"
        }
      ],
      "tocversion": 110005,
      "triggers": {
        "1": {
          "trigger": {
            "auranames": [
              "449581"
            ],
            "auraspellids": [
              "449595"
            ],
            "debuffType": "HELPFUL",
            "event": "Health",
            "fetchTooltip": true,
            "names": [],
            "spellIds": [],
            "subeventPrefix": "SPELL",
            "subeventSuffix": "_CAST_START",
            "type": "aura2",
            "unit": "player",
            "useExactSpellId": false,
            "useName": true
          },
          "untrigger": []
        },
        "activeTriggerMode": -10
      },
      "uid": "ZuXUCeWJZxQ",
      "url": "https://wago.io/MVN1rq_Hs/1",
      "useAdjustededMax": false,
      "useAdjustededMin": false,
      "useCooldownModRate": true,
      "version": 1,
      "wagoID": "MVN1rq_Hs",
      "width": 32,
      "xOffset": 0,
      "yOffset": 0,
      "zoom": 0.3
    },
    {
      "actions": {
        "finish": [],
        "init": [],
        "start": []
      },
      "adjustedMax": "",
      "adjustedMin": "",
      "alpha": 1,
      "anchorFrameType": "SCREEN",
      "anchorPoint": "CENTER",
      "animation": {
        "finish": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "main": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "start": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        }
      },
      "authorOptions": [],
      "color": [
        1,
        1,
        1,
        1
      ],
      "conditions": [],
      "config": [],
      "cooldown": true,
      "cooldownEdge": false,
      "cooldownSwipe": true,
      "cooldownTextDisabled": false,
      "desaturate": false,
      "frameStrata": 1,
      "height": 32,
      "icon": true,
      "iconSource": -1,
      "id": "Ovi'nax's Mercurial Egg BUFF 3",
      "information": [],
      "internalVersion": 78,
      "inverse": false,
      "keepAspectRatio": true,
      "load": {
        "class": {
          "multi": []
        },
        "itemequiped": [
          220305
        ],
        "size": {
          "multi": []
        },
        "spec": {
          "multi": []
        },
        "talent": {
          "multi": []
        },
        "use_itemequiped": true
      },
      "progressSource": [
        -1,
        ""
      ],
      "regionType": "icon",
      "selfPoint": "CENTER",
      "semver": "1.0.0",
      "source": "import",
      "subRegions": [
        {
          "type": "subbackground"
        },
        {
          "border_color": [
            0,
            0,
            0,
            1
          ],
          "border_edge": "Square Full White",
          "border_offset": 0,
          "border_size": 1,
          "border_visible": true,
          "type": "subborder"
        },
        {
          "glow": true,
          "glowBorder": false,
          "glowColor": [
            1,
            1,
            1,
            1
          ],
          "glowDuration": 1,
          "glowFrequency": 0.25,
          "glowLength": 10,
          "glowLines": 8,
          "glowScale": 1,
          "glowThickness": 1,
          "glowType": "Proc",
          "glowXOffset": 0,
          "glowYOffset": 0,
          "type": "subglow",
          "useGlowColor": true
        }
      ],
      "tocversion": 110005,
      "triggers": {
        "1": {
          "trigger": {
            "auranames": [
              "445560"
            ],
            "auraspellids": [
              "445560"
            ],
            "debuffType": "HELPFUL",
            "event": "Health",
            "fetchTooltip": false,
            "names": [],
            "spellIds": [],
            "subeventPrefix": "SPELL",
            "subeventSuffix": "_CAST_START",
            "type": "aura2",
            "unit": "player",
            "useExactSpellId": false,
            "useName": true
          },
          "untrigger": []
        },
        "activeTriggerMode": -10
      },
      "uid": "TRNJ0BZqyn1",
      "url": "https://wago.io/MVN1rq_Hs/1",
      "useAdjustededMax": false,
      "useAdjustededMin": false,
      "useCooldownModRate": true,
      "version": 1,
      "wagoID": "MVN1rq_Hs",
      "width": 32,
      "xOffset": 0,
      "yOffset": 0,
      "zoom": 0.3
    }
  ],
  "d": {
    "actions": {
      "finish": [],
      "init": [],
      "start": []
    },
    "align": "CENTER",
    "alpha": 1,
    "anchorFrameType": "SCREEN",
    "anchorPoint": "CENTER",
    "animate": false,
    "animation": {
      "finish": {
        "duration_type": "seconds",
        "easeStrength": 3,
        "easeType": "none",
        "type": "none"
      },
      "main": {
        "duration_type": "seconds",
        "easeStrength": 3,
        "easeType": "none",
        "type": "none"
      },
      "start": {
        "duration_type": "seconds",
        "easeStrength": 3,
        "easeType": "none",
        "type": "none"
      }
    },
    "arcLength": 360,
    "authorOptions": [],
    "backdropColor": [
      1,
      1,
      1,
      0.5
    ],
    "border": false,
    "borderBackdrop": "Blizzard Tooltip",
    "borderColor": [
      0,
      0,
      0,
      1
    ],
    "borderEdge": "Square Full White",
    "borderInset": 1,
    "borderOffset": 4,
    "borderSize": 2,
    "centerType": "LR",
    "columnSpace": 1,
    "conditions": [],
    "config": [],
    "constantFactor": "RADIUS",
    "frameStrata": 1,
    "fullCircle": true,
    "gridType": "RD",
    "gridWidth": 5,
    "groupIcon": "5948240",
    "grow": "LEFT",
    "id": "Ovi'nax's Mercurial Egg 2",
    "information": [],
    "internalVersion": 78,
    "limit": 5,
    "load": {
      "class": {
        "multi": []
      },
      "size": {
        "multi": []
      },
      "spec": {
        "multi": []
      },
      "talent": {
        "multi": []
      }
    },
    "radius": 200,
    "regionType": "dynamicgroup",
    "rotation": 0,
    "rowSpace": 1,
    "scale": 1,
    "selfPoint": "RIGHT",
    "semver": "1.0.0",
    "sort": "none",
    "sortHybridTable": {
      "Ovi'nax's Mercurial Egg BUFF 1": false,
      "Ovi'nax's Mercurial Egg BUFF 2": false,
      "Ovi'nax's Mercurial Egg BUFF 3": false
    },
    "source": "import",
    "space": 2,
    "stagger": 0,
    "stepAngle": 15,
    "subRegions": [],
    "tocversion": 110005,
    "triggers": [
      {
        "trigger": {
          "debuffType": "HELPFUL",
          "event": "Health",
          "names": [],
          "spellIds": [],
          "subeventPrefix": "SPELL",
          "subeventSuffix": "_CAST_START",
          "type": "aura2",
          "unit": "player"
        },
        "untrigger": []
      }
    ],
    "uid": "FthdwogfsKa",
    "url": "https://wago.io/MVN1rq_Hs/1",
    "useLimit": false,
    "version": 1,
    "wagoID": "MVN1rq_Hs",
    "xOffset": -175.1068898201,
    "yOffset": -79.96422873603
  },
  "m": "d",
  "s": "5.17.4",
  "v": 1421,
  "wagoID": "MVN1rq_Hs"
}
